# Generated by Django 6.0.4 on 2026-04-25 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina',
            options={'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.AlterModelOptions(
            name='nota',
            options={'verbose_name_plural': 'Notas'},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'verbose_name_plural': 'Turmas'},
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='valor_nota',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='data_lancamento',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='ano_lectivo',
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nota',
            name='estudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_aluno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turma',
            name='docente',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turma',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
